version: '2'

services:
  ggumtle-frontend:
    container_name: ggumtle-frontend
    image: $REGISTRY/ggumtle-frontend:$TAG
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt
      - $HOME/ggumtle/frontend:/app/dist/data
      - /home/ubuntu/nginx/sites/sites-enabled:/etc/nginx/sites-enabled
    restart: unless-stopped

  ggumtle-backend:
    container_name: ggumtle-backend
    image: $REGISTRY/ggumtle-backend:$TAG
    ports:
      - "8081:8081"
    volumes:
      - $HOME/ggumtle/backend/logs:/app/logs
      - $HOME/ggumtle/image:/image
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - TZ: "Asia/Seoul"
    restart: unless-stopped